name: Build CentOS 7 Buildbox Assets Images
run-name: Build CentOS 7 Buildbox Assets Images
on:
  # Only allow manual triggers
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  BUILDBOX_BASE_NAME: ghcr.io/gravitational/teleport-buildbox

jobs:
  buildbox-centos7-assets:
    name: Build CentOS 7 Asset Buildbox
    strategy:
      matrix:
        # Build assets on x86 and ARM64.
        runner: [ ubuntu-22.04-32core, ['self-hosted', 'linux', 'arm64'] ]
    # Use bigger worker. Clang takes a while to build.
    runs-on: ${{ matrix.runner }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Teleport
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # We need to keep env vars in sync, so, we can't use standard build actions
      - name: Build buildbox assets image
        run: cd build.assets && make build-centos7-assets

      - name: Docker push the latest built image
        run: docker push $(docker images -a --format '{{.Repository}}:{{.Tag}}'| head -1)
